"use client";

import { motion } from "framer-motion";
import { Sparkles, AlertCircle } from "lucide-react";
import { cn, getRiskColor } from "@/lib/utils";
import type { AISummary } from "@/types";

interface AISummaryCardProps {
  summary: AISummary | null;
  isLoading: boolean;
}

export function AISummaryCard({ summary, isLoading }: AISummaryCardProps) {
  if (isLoading) {
    return (
      <div className="glass-card p-5">
        <div className="mb-3 flex items-center gap-2">
          <div className="skeleton h-5 w-5 rounded" />
          <div className="skeleton h-4 w-40" />
        </div>
        <div className="space-y-2">
          <div className="skeleton h-3 w-full" />
          <div className="skeleton h-3 w-5/6" />
          <div className="skeleton h-3 w-4/6" />
        </div>
      </div>
    );
  }

  if (!summary) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 12 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.4, ease: [0.16, 1, 0.3, 1] }}
      className="glass-card overflow-hidden"
    >
      {/* Header */}
      <div className="flex items-center justify-between border-b border-white/[0.06] px-5 py-3">
        <div className="flex items-center gap-2">
          <Sparkles className="h-4 w-4 text-accent-blue" aria-hidden="true" />
          <h3 className="text-sm font-semibold text-text-primary">
            AI Situation Summary
          </h3>
        </div>
        <div
          className={cn(
            "rounded-full px-2.5 py-0.5 text-[10px] font-bold uppercase tracking-wider",
            summary.riskLevel === "critical" && "bg-red-500/15 text-red-400",
            summary.riskLevel === "high" && "bg-orange-500/15 text-orange-400",
            summary.riskLevel === "medium" && "bg-amber-500/15 text-amber-400",
            summary.riskLevel === "low" && "bg-emerald-500/15 text-emerald-400"
          )}
          role="status"
          aria-label={`Risk level: ${summary.riskLevel}`}
        >
          {summary.riskLevel} risk
        </div>
      </div>

      {/* Summary Text */}
      <div className="px-5 py-4">
        <p className="text-sm leading-relaxed text-text-secondary">
          {summary.summary}
        </p>
      </div>

      {/* Priority Actions */}
      {summary.priorityActions.length > 0 && (
        <div className="border-t border-white/[0.06] px-5 py-3">
          <p className="mb-2 text-[10px] font-semibold uppercase tracking-wider text-text-muted">
            Priority Actions
          </p>
          <ul className="space-y-1.5" role="list">
            {summary.priorityActions.map((action, i) => (
              <li key={i} className="flex items-start gap-2 text-xs text-text-secondary">
                <AlertCircle
                  className={cn(
                    "mt-0.5 h-3 w-3 shrink-0",
                    i === 0 ? "text-amber-400" : "text-text-muted"
                  )}
                  aria-hidden="true"
                />
                <span>{action}</span>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Timestamp */}
      <div className="border-t border-white/[0.06] px-5 py-2">
        <p className="text-[10px] text-text-muted">
          Generated by Gemini AI • {new Date(summary.timestamp).toLocaleTimeString()}
        </p>
      </div>
    </motion.div>
  );
}
